# Generated by Django 5.2.1 on 2025-05-19 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150, verbose_name='Country')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Region')),
                ('independent', models.CharField(blank=True, max_length=10, verbose_name='Independent')),
                ('google_maps', models.URLField(blank=True, verbose_name='Google maps')),
                ('open_street_map', models.URLField(blank=True, verbose_name='Open street map')),
                ('capital_name', models.CharField(blank=True, max_length=100, verbose_name='Capital Name')),
                ('capital_coordinates', models.CharField(blank=True, max_length=50, verbose_name='Capital Coordinates')),
                ('flag_png', models.URLField(blank=True, verbose_name='Flag (png)')),
                ('flag_svg', models.URLField(blank=True, verbose_name='Flag (svg)')),
                ('flag_alt', models.CharField(blank=True, max_length=255, verbose_name='Flag alt')),
                ('coat_of_arms_png', models.URLField(blank=True, verbose_name='Coat of arms (png)')),
                ('coat_of_arms_svg', models.URLField(blank=True, verbose_name='Coat of arms (svg)')),
                ('borders_with', models.CharField(blank=True, max_length=255, verbose_name='Borders with')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('count_of_requests', models.PositiveIntegerField(default=0, verbose_name='Count of requests')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='Last accessed')),
            ],
        ),
        migrations.CreateModel(
            name='NameCountryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(verbose_name='Probability')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namecountry.country')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namecountry.name')),
            ],
            options={
                'unique_together': {('name', 'country')},
            },
        ),
    ]
